[package]
name = "hanzo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
crossterm = "0.25"
log = "0.4"
simple-logging = "2.0"
clap = { version = "4.1", features = ["derive"] }
